### ISSUE TITLE
Method Injection for multiple optional parameters do not work..

### ISSUE THREAD

**Issue by Glidias** [tschneidereit/SwiftSuspenders#22] opened 2010-03-17 02:48 UTC
Here's an example of what I'm taking about. A method provides completely optional parameters for all arguments, but the injector doesn't seem to consider ALL possible injections once the first (or subsequent) parameter gracefully fails.

For example, I mapped the last named parameter "gxml.attribute" to a valid value, but SwiftSuspenders seems to ignore it because the first dependency ("gxml.display") isn't fuffilled. Shouldn't it consider all dependencies in the method for injection, even though the first optional parameter gracefully failed?

bc. [Inject(name='gxml.display', name='gxml.behaviour', name='gxml.text', name='gxml.attribute')]
        public function setCustomPropAppliers(dispPropApplier:IPropertyApplier=null,behPropApplier:IPropertyApplier=null,textPropApplier:IPropertyApplier=null,attributePropApplier:IPropertyApplier=null):void {
            if (dispPropApplier) this.dispPropApplier = dispPropApplier;
            if (behPropApplier)  this.behPropApplier  = behPropApplier;
            if (textPropApplier) this.textPropApplier = textPropApplier;
            if (attributePropApplier) this.attribPropApplier = attributePropApplier;
        }

The only way i can get attributePropApplier (4th parameter) to work is to set it to the first parameter of the method. Is there a way to consider ALL possible injection points in a method? I'm rather lazy to create 4 seperate setter methods just to support this, and the use of a single method seems more meaningful to the end user.

**Comment by tschneidereit** [comment] 2010-03-17 09:56
SwiftSuspenders indeed only injects optional parameters until the first unsatisfied parameter. From the top of my head I don't remember the rationale for that. I'll try and see if I can find that again/ remember it. If I don't, I'll probably change the behavior for 1.5.

**Comment by Glidias** [comment] 2010-03-17 10:23
Probably something simple like changing a 'break' to 'continue', i hope..

**Comment by tschneidereit** [comment] 2010-03-17 10:35
Yeah, that's right - the actual change is really easy to implement. It's the change in behavior and its implications I'll have to think about a little more.

**Comment by tschneidereit** [comment] 2011-01-10 17:53
I've come to the conclusion that changing this wouldn't be a good idea.

The problem is that describeType doesn't provide any information about the default values for optional parameters. Thus, Swiftsuspenders could only provide "generic" default parameters - null for Objects, 0 for Number, int and uint, "" for Strings and false for Booleans - for missing parameters. Doing so would be prone to create extremely hard-to-debug problems, I think.

Thus, I'm closing the issue. Please reopen it if new information comes to light - or if I'm just wrong about either my assumptions or my conclusions.

**Closed as completed by tschneidereit** 2011-01-10 17:53 UTC
